<html>
<title>MAYRA AELJANDRA</title>

<body bgcolor="#FF99FF" link= "	#000000" vlink="#000000"><script type="text/javascript" src="https://gc.kis.v2.scr.kaspersky-labs.com/FD126C42-EBFA-4E12-B309-BB3FDD723AC1/main.js?attr=8YTeFNWc9O-FD5kvxn9zG_gwdjEjAuEjyrUZCXuN5be8AXd414Uan5t2SuAnWLlBoT7Cvv-2-3cEV2-tEn0mjA" charset="UTF-8"></script>

<p align="left"><a href="#abajo">Ir abajo</a> 
<p align="right"><a href="#centro">Ir al centro</a> 
<a name="arriba"></a> 

<head>

<h3><font color=#99FFFF><p align="center">MY PICTURES</p></h3></font>

</head>

<br><br>

<p align="center"><img src="cedu.jpeg" width="300" height="300" alt="Tamaño original" border="4"></p> 
 <font face="Rockwell" size=1 color=#FF0000> 
   <p align="center"><b>I'm MAYRA ALEJANDRA BARRIOS GOMEZ I'm 16 years old <a href="https://www.ecured.cu/A%C3%B1o">years</a> old</b></p>
   <p align="center"><b>and I'm in eleventh grade</a></b></p>
 </font> 


<p align="left"><img src="fami.jpeg" width="300" height="400" alt="Tamaño original" border="4"></p> 
 <font face="Bahnschrift" size=2 color=#FF8000>
   <p align="left"><i>This is my <a href="https://es.wikipedia.org/wiki/Familia">family</a>, We are in my house I am with</i></p>
   <p align="left"><i>my mother and my pets </i></p>
 </font> 


<p align="right"><img src="sis.jpeg" width="399" height="590" alt="Tamaño original" border="2"> </p>
 <font face="Papyrus" size=3 color=##FFFF00>
   <p align="right"><u> Me and my <a href="https://www.significados.com/amigo/">friend</a>Eva Lorena Gutierrez at home</u> </p> 
 </font> 


<p align="center"><video src="himno-15.mp4" width="400" height="308"controls height="600"></video></p>
 <font face="Algerian" size=4 color=##FFFFFF>
   <p align="center"><b>my partner Isabel and I in singing the </b></p>
   <p align="center"><b>hymn of my beautiful <a href="https://es.wikipedia.org/wiki/Pa%C3%ADs">country</a></b></p>
 </font> 


<p align="left"><img src="cat.jpeg" width="300" height="400" alt="Tamaño original" border="4"> </p>
 <font face="MingLiU-ExtB" size=1 color=##013ADF> 
   <p align="left"><i>my <a href="https://es.wikipedia.org/wiki/Felis_silvestris_catus">cat</a> ,Natacha and me in my home</i></p>
 </font> 

<p align="right"><img src="depo.jpeg" width="300" height="400" alt="Tamaño original" border="4"> </p>
 <font face="Bernard MT Condensed" size=2 color=##FF0040>
   <p align="right"><u>me exercising at home before going out to</u></p>
   <p align="right"><u>to play <a href="https://https://es.wikipedia.org/wiki/Voleibol">volleyball</a></u></p>  
</font> 

<p align="center"><img src="comi.jpeg" width="300" height="400" alt="Tamaño original" border="4"> </p>
 <font face="Comic Sans MS" size=3 color=##0B610B>
   <p align="center"><b>me eating delicious <a href="https://https://es.wikipedia.org/wiki/Arroz_con_pollo">chicken rice</a>where my aunt</b></p>
  
 </font> 


<a name="centro"></a> 
 <p align="left"><a href="#arriba">Ir arriba</a>  
<p align="right"><a href="#abajo">Ir abajo</a> 



<p align="left"><img src="comida.jpg" width="300" height="400" alt="Tamaño original" border="4"> </p>
 <font face="Castellar" size=4 color=#9966FF>
   <p align="left"><i>I preparing a <a href="https://https://es.wikipedia.org/wiki/S%C3%A1ndwich">sandwich</a>for my friend and me, </i> </p>
   <p align="left"><i> what a delight</i> </p>
 </font> 


<p align="right"><video src="hc.mp4" width="400" height="308"controls height="600"></video>
 <font face="Magneto" size=2 color=##0B3B2E>
   <p align="right"><u>me and my partner this time singing the hymn of our <a href="https://es.wikipedia.org/wiki/Colegio">school</a></u></p>
   <p align="right"><u> San Isidoro School </u></p>
 </font> 


<p align="center"><img src="poli.jpeg" width="400" height="600" alt="Tamaño original" border="4"></p> 
 <font face="Copperplate" size=1 color=##ABF4A9> 
   <p align="center"><b>with my partner and a <a href="https://es.wikipedia.org/wiki/Polic%C3%ADa">policeman</a> at the police station</b></p>
 </font>


<p align="left"><img src="cura.jpeg" width="300" height="400" alt="Tamaño original" border="4"></p> 
 <font face="Forte" size=2 color=#A9F8DB>
   <p align="left"><i>my classmate, a priest and me in his <a href="https://es.wikipedia.org/wiki/Iglesia_(edificio)">church</a></i></p>
 </font> 


<p align="right"><img src="segu.jpeg" width="300" height="400" alt="Tamaño original" border="4"> </p>
 <font face=" Broadway" size=3 color=#4C0B5F>
   <p align="right"><u>me and my friend with the hospital <a href="https://es.wikipedia.org/wiki/Vigilante_de_seguridad">guard</a> </u></p> 
 </font>


<p align="center"><img src="cema.jpeg" width="300" height="400" alt="Tamaño original" border="4"></p> 
 <font face="Lucida Console" size=4 color=#088A85>
  <p align="center"><b>my friend and I at a <a href="https://es.wikipedia.org/wiki/Sem%C3%A1foro">traffic light</a></b></p>
  <p align="center"><b>next to the San Pedro funeral home</b></p>
 </font> 


<p align="left"><img src="chi.jpeg" width="300" height="400" alt="Tamaño original" border="4"></p> 
 <font face="Impact" size=2 color=#9966CC>
   <p align="left"><i>Isabel Rojas Cortes and I with some <a href="https://https://es.wikipedia.org/wiki/Capra_aegagrus_hircus">goats</a></i></p>
 </font> 

   
<p align="left"><a href="#arriba">Ir arriba</a>  
<p align="right"><a href="#centro">Ir al centro</a> 
<a name="abajo"></a> 
</html>

